# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Lorenzo Pasco
title: Artificial Intelligence and Data Engineering student
email: pascolorenzo-at-gmail.com
website: https://github.com/lorepas

# Dark Mode (true/false/never)
darkmode: true

# Social links
#twitter_username: facespics
github_username:  lorepas
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
#instagram_username: jameswgrant
linkedin_username: lorenzo-pasco-b8387721b
# xing_username: jekyll
# pinterest_username: jekyll
#youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
#- title: itsgoingto.be
#  icon: fas fa-globe
#  url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name is Lorenzo Pasco and I come from Pisa, Italy. I've earned a Bachelor Degree of Computer Engineering in 2019 at University of Pisa and I'm currently studying for Master Degree in Artificial Intelligence and Data Engineering at University of Pisa.

content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Academic Projects
        link: https://github.com/lorepas?tab=repositories
        # link_text: Project Website
        additional_links:
          - title:  lorepas?tab=repositories
            icon: fab fa-github
            url: https://github.com/lorepas?tab=repositories
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
#        quote: >
#          This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
        description: | # this will include new lines to allow paragraphs
          In my GitHub repository are available all the projects done during my Master's degree career.

#  - title: Experience # Title for the section
#    layout: list # Type of content section (list/text)
#    content:
#      - layout: left
#        title: The Boring Company
#        link: boringcompany.com
#        # link_text: boringcompany.com
#        sub_title: Senior Network System Administrator
#        caption: November 2017 - Present
#        quote: >
#          Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
#        description: | # this will include new lines to allow paragraphs
#            Every company needs its networks properly administered and The Boring Compay is no exception. Digging holes is hard and I play my part making sure the whole company stays connected. I lead a team of 5 people and enjoy driving the company to try new technologies.

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: University of Pisa
        caption: 2019 - Currently
        sub_title: Master's degree in Artificial Intelligence and Data Engineering
#        quote: >
#          Established in 1636, Harvard is the oldest higher education institution in the United States, and is widely regarded in terms of its influence, reputation, and academic pedigree as a leading university in not just the US but also the world.
        description: | # this will include new lines to allow paragraphs
          * Use of Python programming language
          * Use of MongoDB and Neo4j to handle NoSQL database
          * Use of TensorFlow and Keras libraries for automatic learning of neural networks
          * Use of Hadoop and Spark framework to deploy distributed applications
          * Lightweight virtualization technique with Docker
          * Use of Kubernetes
          * Implementation of Deep and Convolutional Neural Networks
          * Notions about Cybersecurity
          * Knowledge about the main classification and clustering algorithms

      - layout: left
        title: University of Pisa
        caption: 2014 - 2019
        sub_title: Bachelor's degree in Computer Engineering
        description: | # this will include new lines to allow paragraphs
          * Reasoning and logical organization
          * Mathematical skills
          * Knowledge about a computer and how to connect it in a computers' network
          * Handling a MySQL database
          * Develop a web site using HTML, PHP, JavaScript and CSS
          * Implementation of application using C, C++ and Java as languages programming
        
  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in networks and software engineering some of my other interests and hobbies are:
      - Rock climbing
      - Gaming
      - Knitting


# Footer
footer_show_references: false
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
